{
 "title": "Service Drilldown",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "orders_api : orders_api,payments_worker : payments_worker,notification_svc : notification_svc"
   }
  ]
 },
 "panels": [
  {
   "title": "Error Budget Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "slo:$service:error_budget_remaining_ratio * 100"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "slo:$service:latency_p95_seconds * 1000"
    }
   ]
  },
  {
   "title": "Requests (28d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "slo:$service:requests_total_28d"
    }
   ]
  },
  {
   "title": "Burn Rate (1h / 6h / 24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "slo:$service:burnrate_1h", "legendFormat": "1h" },
    { "expr": "slo:$service:burnrate_6h", "legendFormat": "6h" },
    { "expr": "slo:$service:burnrate_24h", "legendFormat": "24h" }
   ]
  },
  {
   "title": "Dependency Liveness (up)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "up{job=~\"orders-api|payments-worker|notification-svc|mock-gateway|mock-receiver\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}